#!/bin/bash
# HPC environment bootstrap for ced_ml job wrappers.
#
# Sourced by every wrapper script generated by ced_ml.hpc (both per-seed
# training and downstream aggregation). Idempotent, non-interactive, silent
# on success. Extend per-cluster without touching library code.
#
# Contract: after sourcing, `which python3` must resolve to the project venv
# and `python3 -c "import pyarrow"` must succeed with the pyarrow version
# pinned in analysis/pyproject.toml (not the system-provided one).

set -u

# Resolve project root from this script's location: analysis/scripts/hpc_activate.sh
# -> analysis/ -> project root
_HPC_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
_ANALYSIS_DIR="$(dirname "$_HPC_SCRIPT_DIR")"
_PROJECT_ROOT="$(dirname "$_ANALYSIS_DIR")"

# --- Cluster bootstrap ---------------------------------------------------
# Minerva (Icahn School of Medicine at Mount Sinai):
#   The venv is linked against /hpc/packages/minerva-rocky9/python/3.12.5.
#   Loading the python module puts libpython3.12.so.1.0 on the dynamic
#   library search path and prepends /hpc/packages/.../py_packages to
#   PYTHONPATH. The module-exported PYTHONPATH MUST be cleared, otherwise
#   it shadows the venv's own site-packages and pandas/pyarrow get loaded
#   from the cluster-wide install (wrong version, parquet read failures).
if [ -f /etc/profile.d/modules.sh ]; then
    # shellcheck disable=SC1091
    source /etc/profile.d/modules.sh
    if command -v module &>/dev/null; then
        module load python/3.12.5 2>/dev/null || true
        unset PYTHONPATH
    fi
fi

# --- Activate project venv ------------------------------------------------
# Prefer ``venv`` over ``.venv`` for backward compatibility with existing
# wrappers; fall back to ``.venv`` for local dev environments.
if [ -f "${_ANALYSIS_DIR}/venv/bin/activate" ]; then
    # shellcheck disable=SC1091
    source "${_ANALYSIS_DIR}/venv/bin/activate"
elif [ -f "${_ANALYSIS_DIR}/.venv/bin/activate" ]; then
    # shellcheck disable=SC1091
    source "${_ANALYSIS_DIR}/.venv/bin/activate"
else
    echo "[$(date '+%F %T')] FATAL: no venv found under ${_ANALYSIS_DIR}" >&2
    return 1 2>/dev/null || exit 1
fi
